# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 332109c12caa04796108f976e83b4578dc9a241cab932e9e559efcb260714a16682a40df5b45da334298760f08e413125a09c7ae61ff6b84e0edca376b74b37d

test:
  secret_key_base: 9cba918782fa8464b76739b8b3d047c766905b9425b92271a12224207974699e6494e18f3cedc16fd032202e4cf4672ae65f2c2995d45ed1733cfd6d849abf56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
